Shellcheck fixes

diff --git a/tests/all_pages_reachable b/tests/all_pages_reachable
--- a/tests/all_pages_reachable
+++ b/tests/all_pages_reachable
@@ -3,7 +3,7 @@ set -e
 
 if PROCESS=$(pgrep ".*8666.*" | grep python)
 then
-    echo -e "Server already running, aborting\n$PROCESS" 1>&2
+    echo -e "Server already running, aborting\\n$PROCESS" 1>&2
     exit 1
 fi
 
@@ -54,7 +54,7 @@ pushd "$rendered" > /dev/null
     # Delete the directory *and* kill the server when we exit
     trap cleanup EXIT
 
-    printf "Waiting for server to start (PID $SERVER_PID)..." 1>&2
+    printf "Waiting for server to start (PID %s)..." "$SERVER_PID" 1>&2
 
     while true
     do
diff --git a/tests/tidy_html5 b/tests/tidy_html5
--- a/tests/tidy_html5
+++ b/tests/tidy_html5
@@ -26,7 +26,8 @@ function check {
     fi
 
     # Otherwise, abort
-    echo -e "Tidy failed for '$1':\n\n$STDERR\n\n---\nEnd report for '$1'\n\n" 1>&2
+    echo -e "Tidy failed for '$1':\\n\\n$STDERR\\n" 1>&2
+    echo -e "---\\nEnd report for '$1'\\n\\n"       1>&2
     return 1
 }
 
