Made commands more portable (no /dev/stderr, no nix-shell, etc.)

diff --git a/tests/cleanupTables b/tests/cleanupTables
--- a/tests/cleanupTables
+++ b/tests/cleanupTables
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 function fail {
-    echo "FAIL: $1" >> /dev/stderr
+    echo "FAIL: $1" 1>&2
     exit 1
 }
 
@@ -18,7 +18,7 @@ do
     # Skip empty
     [[ -n "$INPUT" ]] || continue
 
-    CLEANED=$(echo "$INPUT" | ./static/cleanup)
+    CLEANED=$(echo "$INPUT" | cleanup)
 
     echo "$CLEANED" | grep '<span' > /dev/null &&
         fail "Didn't strip span: $CLEANED"
@@ -30,4 +30,4 @@ do
         fail "Didn't remove parent <p>"
 done < <(inputs)
 
-echo "Success" >> /dev/stderr
+echo "Success" 1>&2
diff --git a/tests/empty_panpipe_blocks_stripped b/tests/empty_panpipe_blocks_stripped
--- a/tests/empty_panpipe_blocks_stripped
+++ b/tests/empty_panpipe_blocks_stripped
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
 
 function fail {
-    echo "FAIL: $1" >> /dev/stderr
+    echo "FAIL: $1" 1>&2
     exit 1
 }
 
-OUTPUT=$(echo '<pre><code></code></pre>' | ./static/render_page)
+OUTPUT=$(echo '<pre><code></code></pre>' | render_page)
 
 echo "$OUTPUT" | grep '<code>' > /dev/null && fail "Didn't strip <code>"
 echo "$OUTPUT" | grep '<pre>'  > /dev/null && fail "Didn't strip <pre>"
 
-echo "Success" >> /dev/stderr
+echo "Success" 1>&2
diff --git a/tests/have_all_posts b/tests/have_all_posts
--- a/tests/have_all_posts
+++ b/tests/have_all_posts
@@ -1,5 +1,4 @@
-#! /usr/bin/env nix-shell
-#! nix-shell -i bash -p bash xidel
+#!/usr/bin/env bash
 
 LINKS=$(xidel - -q --extract "//a/@href" < rendered/blog.html)
 
@@ -11,12 +10,12 @@ do
     DEST="/blog/$NAME.html"
     if [[ ! -e "rendered$DEST" ]]
     then
-        echo "Can't find rendered$DEST" >> /dev/stderr
+        echo "Can't find rendered$DEST" 1>&2
         exit 1
     fi
     if ! echo "$LINKS" | grep "$NAME" > /dev/null
     then
-        echo "blog/$NAME.html doesn't appear in blog.html" >> /dev/stderr
+        echo "blog/$NAME.html doesn't appear in blog.html" 1>&2
         exit 1
     fi
 done < <(find blog -type f)
diff --git a/tests/have_all_projects b/tests/have_all_projects
--- a/tests/have_all_projects
+++ b/tests/have_all_projects
@@ -1,24 +1,23 @@
-#! /usr/bin/env nix-shell
-#! nix-shell -i bash -p xidel bash
+#!/usr/bin/env bash
 
 ERR=0
-while read -r SOURCE
+while read -r NAME
 do
-    [[ "x$SOURCE" = "xprojects/index.html" ]] && continue
+    [[ "x$NAME" = "xrendered/projects/index.html" ]] && continue
 
-    NAME=$(echo "$SOURCE" | rev | cut -d '.' -f 2- | rev)
-    DEST="./$NAME.html"
+    NOREND=$(echo "$NAME" | sed -e 's@^rendered/@@g')
+    DEST="./$NOREND"
     if [[ ! -e "rendered/$DEST" ]]
     then
-        echo "Can't find rendered$DEST" >> /dev/stderr
+        echo "Can't find rendered/$DEST" 1>&2
         ERR=1
     fi
     LINK=$(xidel - -q --extract "//a[@href='$DEST']/@href" < rendered/projects.html)
     if ! echo "$LINK" | grep "$NAME" > /dev/null
     then
-        echo "$NAME.html doesn't appear in projects.html" >> /dev/stderr
+        echo "$NAME doesn't appear in projects.html" 1>&2
         ERR=1
     fi
-done < <(find projects -type f -name "index.*")
+done < <(find rendered/projects -type f -name "index.*")
 
 exit "$ERR"
diff --git a/tests/posts_have_titles b/tests/posts_have_titles
--- a/tests/posts_have_titles
+++ b/tests/posts_have_titles
@@ -1,11 +1,10 @@
-#! /usr/bin/env nix-shell
-#! nix-shell -i bash -p bash xidel
+#!/usr/bin/env bash
 xidel - -q --extract "//div[@id='content']//ul/li/a" < rendered/blog.html |
     while read -r TITLE
     do
         if [[ -z "$TITLE" ]]
         then
-            echo "Missing title!" >> /dev/stderr
+            echo "Missing title!" 1>&2
             exit 1
         fi
     done
diff --git a/tests/tidy_html5 b/tests/tidy_html5
--- a/tests/tidy_html5
+++ b/tests/tidy_html5
@@ -1,8 +1,7 @@
-#! /usr/bin/env nix-shell
-#! nix-shell -i bash -p bash tidy-html5
+#!/usr/bin/env bash
 
 function fail {
-    echo "FAIL: $1" >> /dev/stderr
+    echo "FAIL: $1" 1>&2
     exit 1
 }
 
@@ -22,12 +21,12 @@ function check {
     # Ignore things we don't care too much about (e.g. READMEs)
     if lax "$1"
     then
-        echo "Ignored tidy errors for '$1'" >> /dev/stderr
+        echo "Ignored tidy errors for '$1'" 1>&2
         return
     fi
 
     # Otherwise, abort
-    echo -e "Tidy failed for '$1':\n\n$STDERR\n\n---\nEnd report for '$1'\n\n" >> /dev/stderr
+    echo -e "Tidy failed for '$1':\n\n$STDERR\n\n---\nEnd report for '$1'\n\n" 1>&2
     return 1
 }
 
