Fix JS optimisation pages, added tests to prevent regression

diff --git a/tests/code_not_indented b/tests/code_not_indented
--- a/tests/code_not_indented
+++ b/tests/code_not_indented
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -e
 
 # Indenting HTML is nice, but if we do it on pre/code blocks then the whitespace
 # appears verbatim in the page.
@@ -6,15 +7,9 @@
 # shellcheck disable=SC2154
 F="$rendered/blog/2017-01-14-rss_to_maildir.html"
 
-[[ -f "$F" ]] || {
-    echo "Example file '$F' not found in '$PWD'" 1>&2
-    exit 1
-}
+[[ -f "$F" ]] || fail "Example file '$F' not found in '$PWD'"
 
-if grep ' [ ]*<pre' < "$F"
-then
-    echo "Source code is indented; this will be visible on the page" 1>&2
-    exit 1
-fi
+grep ' [ ]*<pre' < "$F" &&
+    fail "Source code is indented; this will be visible on the page"
 
 exit 0
diff --git a/tests/posts_have_titles b/tests/posts_have_titles
--- a/tests/posts_have_titles
+++ b/tests/posts_have_titles
@@ -1,11 +1,9 @@
 #!/usr/bin/env bash
+set -e
+
 # shellcheck disable=SC2154
 xidel - -q --extract "//div[@id='content']//ul/li/a" < "$rendered"/blog.html |
     while read -r TITLE
     do
-        if [[ -z "$TITLE" ]]
-        then
-            echo "Missing title!" 1>&2
-            exit 1
-        fi
+        [[ -n "$TITLE" ]] || fail "Missing title!"
     done
