Don't make copies of the site during testing

diff --git a/tests/have_all_posts b/tests/have_all_posts
--- a/tests/have_all_posts
+++ b/tests/have_all_posts
@@ -1,16 +1,16 @@
 #!/usr/bin/env bash
 
-LINKS=$(xidel - -q --extract "//a/@href" < rendered/blog.html)
+LINKS=$(xidel - -q --extract "//a/@href" < "$rendered/blog.html")
 
 while read -r SOURCE
 do
-    [[ "x$SOURCE" = "xrendered/blog/index.html" ]] && continue
+    [[ "x$SOURCE" = "x$rendered/blog/index.html" ]] && continue
 
     NAME=$(basename "$SOURCE" | rev | cut -d '.' -f 2- | rev)
     DEST="/blog/$NAME.html"
-    if [[ ! -e "rendered$DEST" ]]
+    if [[ ! -e "$rendered$DEST" ]]
     then
-        echo "Can't find rendered$DEST" 1>&2
+        echo "Can't find $rendered$DEST" 1>&2
         exit 1
     fi
     if ! echo "$LINKS" | grep "$NAME" > /dev/null
@@ -18,6 +18,6 @@ do
         echo "blog/$NAME.html doesn't appear in blog.html" 1>&2
         exit 1
     fi
-done < <(find rendered/blog -type f -o -type l)
+done < <(find "$rendered/blog" -type f -o -type l)
 
 exit 0
diff --git a/tests/have_all_projects b/tests/have_all_projects
--- a/tests/have_all_projects
+++ b/tests/have_all_projects
@@ -3,21 +3,22 @@
 ERR=0
 while read -r NAME
 do
-    [[ "x$NAME" = "xrendered/projects/index.html" ]] && continue
+    [[ "x$NAME" = "x$rendered/projects/index.html" ]] && continue
 
-    NOREND=$(echo "$NAME" | sed -e 's@^rendered/@@g')
+    NOREND=$(echo "$NAME" | sed -e 's@^/nix/store/[^/]*/@@g')
     DEST="./$NOREND"
-    if [[ ! -e "rendered/$DEST" ]]
+    if [[ ! -e "$rendered/$DEST" ]]
     then
-        echo "Can't find rendered/$DEST" 1>&2
+        echo "Can't find $rendered/$DEST" 1>&2
         ERR=1
     fi
-    LINK=$(xidel - -q --extract "//a[@href='$DEST']/@href" < rendered/projects.html)
+    LINK=$(xidel - -q --extract \
+                 "//a[@href='$DEST']/@href" < "$rendered/projects.html")
     if ! echo "$LINK" | grep "$DEST" > /dev/null
     then
         echo "$NAME ($DEST) doesn't appear in projects.html" 1>&2
         ERR=1
     fi
-done < <(find rendered/projects -name "index.*")
+done < <(find "$rendered/projects" -name "index.*")
 
 exit "$ERR"
diff --git a/tests/redirect_posts b/tests/redirect_posts
--- a/tests/redirect_posts
+++ b/tests/redirect_posts
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 
-for F in rendered/blog/*.html
+for F in "$rendered"/blog/*.html
 do
   NAME=$(basename "$F")
-  grep "$NAME" < rendered/index.php > /dev/null || {
-    echo "Couldn't find '$NAME' in rendered/index.php" 1>&2
+  grep "$NAME" < "$rendered"/index.php > /dev/null || {
+    echo "Couldn't find '$NAME' in $rendered/index.php" 1>&2
     exit 1
   }
 done
