Render repo pages individually

diff --git a/static/getDeps b/static/getDeps
--- a/static/getDeps
+++ b/static/getDeps
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 [[ -n "$1" ]] || exit 0
 [[ -f "$1" ]] || {
-    echo "Can't get dependencies of '$1'" >> /dev/stderr
+    echo "Can't get dependencies of '$1'" 1>&2
     exit 1
 }
 
diff --git a/static/procedural/includePic b/static/procedural/includePic
--- a/static/procedural/includePic
+++ b/static/procedural/includePic
@@ -3,7 +3,7 @@ TEMP=$(pwd)
 convert "$1.ppm" "$1.png"
 DIR=$(dirname "$0")
 cd "$DIR" || {
-    echo "Couldn't cd to '$DIR'" >> /dev/stderr
+    echo "Couldn't cd to '$DIR'" 1>&2
     exit 1
 }
-"../file2img.sh" "$TEMP/$1" < "$TEMP/$1.png" | pandoc -t json
+file2img "$TEMP/$1" < "$TEMP/$1.png" | pandoc -t json
