Simplify render_page
We always have a SOURCE, SOURCE_PATH and DEST and we always output HTML. This
lets us avoid many of the branches we were doing, in favour of a single happy
path; and it lets us turn that into a pipeline.

diff --git a/static/render_page b/static/render_page
--- a/static/render_page
+++ b/static/render_page
@@ -2,105 +2,35 @@
 set -e
 set -o pipefail
 
-# Common options
- IN_OPTIONS=(-t json)
-OUT_OPTIONS=(-f json -s --mathml --template "$defaultTemplate")
+# Capture and discard stdin, to avoid pandoc waiting on user input
+if [ -t 0 ]; then INPUT=""; else INPUT=$(cat); fi
+unset INPUT
 
-# If the filename contains a date, provide it to the output template
-if echo "$SOURCE" | grep -P "\d{4}-\d{2}-\d{2}" > /dev/null
+# Common options. Make sure SOURCE is at the end of IN_OPTIONS.
+ IN_OPTIONS=(-t json "$SOURCE")
+OUT_OPTIONS=(-f json -t html -s --mathml --template "$defaultTemplate")
+
+# Provide 'path' arg for our View Source links.
+P="$SOURCE"
+[[ -n "$SOURCE_PATH" ]] && P="$SOURCE_PATH"
+OUT_OPTIONS+=(-M "path=\"$P\"")
+
+# If filename contains a date (e.g. blogs), provide it to the output template
+if D=$(echo "$SOURCE" | grep -om1 -P "\d{4}-\d{2}-\d{2}")
 then
-    D=$(echo "$SOURCE" | grep -oP "\d{4}-\d{2}-\d{2}" | head -n1)
     OUT_OPTIONS+=(-M "date=\"$D\"")
 fi
 
-# If we're writing to a file, tell pandoc so it can guess the format. Also add
-# the path from the output to the root as a variable so we can use relative
-# links.
-if [[ -n "$DEST" ]]
-then
-    OUT_OPTIONS+=(-o "$DEST")
-fi
-
-# See if we have a path to the source, for giving to pandoc
-if [[ -n "$SOURCE_PATH" ]]
-then
-    OUT_OPTIONS+=(-M "path=\"$SOURCE_PATH\"")
-fi
-
-# If we're reading from a file, use it as pandoc's input, and provide the path
-# as a variable for the output template.
-if [[ -n "$SOURCE" ]]
-then
-    if [[ -z "$SOURCE_PATH" ]]
-    then
-        OUT_OPTIONS+=(-M "path=\"$SOURCE\"")
-    fi
-    IN_OPTIONS+=("$SOURCE") # This should go at the end; add extra options above
-fi
-
-# Capture programmatic input using cat, i.e. don't prompt the user if there's
-# none available
-if [ -t 0 ]
-then
-    INPUT=""
-else
-    INPUT=$(cat)
-fi
-
-echo "Running pandoc, capturing output for post-processing" 1>&2
-echo "Pandoc input  options: ${IN_OPTIONS[@]}"              1>&2
-echo "Pandoc output options: ${OUT_OPTIONS[@]}"             1>&2
-
 # We don't use pandoc's --filter option, as it buffers stderr which makes
-# debugging harder
-OUTPUT=$(pandoc "${IN_OPTIONS[@]}" | panpipe | panhandle |
-         pandoc "${OUT_OPTIONS[@]}") || {
-    echo -e "Rendering pipeline failed\n$OUTPUT\n" 1>&2
-    exit 1
-}
+# debugging harder. 'postprocessor' comes from the file's YAML (default: 'cat')
+pandoc "${IN_OPTIONS[@]}"      |
+    panpipe                    |
+    panhandle                  |
+    pandoc "${OUT_OPTIONS[@]}" |
+    cleanup                    |
+    "${postprocessor:-cat}"    > "$DEST" || fail "Rendering pipeline failed"
 
-# If output was written to $DEST, read it back. This allows pandoc to determine
-# the output format from the filename.
-if [[ -n "$DEST" ]]
-then
-    if [[ -e "$DEST" ]]
-    then
-        OUTPUT=$(cat "$DEST")
-        rm "$DEST"
-    else
-        echo "File '$DEST' wasn't created, aborting" 1>&2
-        exit 1
-    fi
-fi
+# Check output
 
-# Abort if our OUTPUT is empty
-echo "$OUTPUT" | grep '[^ \n\t]' > /dev/null || {
-    [[ -e "$DEST" ]] && rm "$DEST"
-    echo "Output is empty, aborting" 1>&2
-    exit 1
-}
-
-# Perform post-processing before outputting the result
-CLEANED=$(echo "$OUTPUT" | cleanup)
-unset OUTPUT
-
-# Next, perform any custom postprocessing. This is specified by the file's YAML,
-# and passed to us via the 'postprocessor' environment variable.
-if [[ -n "$postprocessor" ]]
-then
-    echo "Running postprocessor '$postprocessor'" 1>&2
-    POSTPROCESSED=$(echo "$CLEANED" | "$postprocessor")
-else
-    POSTPROCESSED="$CLEANED"
-fi
-unset CLEANED
-
-# Send stdin to its final destination, either stdout or $DEST
-if [[ -n "$DEST" ]]
-then
-    echo "Finished postprocessing, writing to '$DEST'" 1>&2
-    echo "$POSTPROCESSED" > "$DEST"
-else
-    echo "Finished postprocessing, writing to stdout" 1>&2
-    echo "$POSTPROCESSED"
-fi
+[[ -e "$DEST" ]]                      || fail "Error: '$DEST' wasn't created"
+grep '[^ \n\t]' < "$DEST" > /dev/null || fail "Error: Output is empty"
